apiVersion: apps/v1
kind: Deployment
metadata:
  name: jinja-render-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jinja-render-app
  template:
    metadata:
      labels:
        app: jinja-render-app
    spec:
      containers:
      - name: nginx
        image: muzammilpeer/jinja-render-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jinja-render-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: jinja-render-app
